const LANG = {
        new_connection: "<?= lang('App.connection.new_connection') ?>",
        manage_connections: "<?= lang('App.connection.manage_connections') ?>",
        select_connection: "<?= lang('App.connection.select_connection') ?>",
        confirm_delete_connection: "<?= lang(
            'App.connection.confirm_delete_connection',
        ) ?>",
        invalid_number: "<?= lang('App.general.invalid_number') ?>",
        new_master_password: "<?= lang('App.master_password.new') ?>",
        ask_master_password: "<?= lang('App.master_password.ask_prompt') ?>",
        prompt_connection_name: "<?= lang(
            'App.connection.prompt_connection_name',
        ) ?>",
        error_decrypting_password: "<?= lang(
            'App.master_password.error_decrypting',
        ) ?>",
        no_saved_connections: "<?= lang(
            'App.connection.no_saved_connections',
        ) ?>",
        connection_deleted: "<?= lang('App.connection.connection_deleted') ?>",
        connection: "<?= lang('App.connection.title') ?>",
        invalid_master_password: "<?= lang('App.master_password.invalid') ?>",
        confirm_clear_connections: "<?= lang(
            'App.connection.confirm_clear_connections',
        ) ?>",
        executing: "<?= lang('App.workspace.workspace') ?>",
        execute: "<?= lang('App.workspace.execute') ?>",
        changing: "<?= lang('App.connection.changing') ?>",
        error_alter_database: "<?= lang(
            'App.feedback.error_alter_database',
        ) ?>",
        intellisense_error: "<?= lang('App.feedback.intellisense_error') ?>",
        confirm_delete_script: "<?= lang('App.scripts.confirm_delete') ?>",
        prompt_script_name: "<?= lang('App.scripts.prompt_name') ?>",
        script_name_default: "<?= lang('App.scripts.default_name') ?>",
        empty_script_alert: "<?= lang('App.scripts.empty_alert') ?>",
        empty_shared_script_alert: "<?= lang(
            'App.scripts.empty_shared_alert',
        ) ?>",
        prompt_shared_name: "<?= lang('App.scripts.prompt_shared_name') ?>",
        shared_name_default: "<?= lang('App.scripts.shared_default_name') ?>",
        prompt_author: "<?= lang('App.scripts.prompt_author') ?>",
        author_default: "<?= lang('App.scripts.author_default') ?>",
        share_fail: "<?= lang('App.scripts.share_fail') ?>",
        confirm_delete_shared: "<?= lang(
            'App.scripts.confirm_delete_shared',
        ) ?>",
        delete_shared_fail: "<?= lang('App.scripts.delete_shared_fail') ?>",
        format_fail: "<?= lang('App.feedback.format_fail') ?>",
        exec_error: "<?= lang('App.feedback.exec_error') ?>",
        no_results_found: "<?= lang('App.feedback.no_results_found') ?>",
        empty_result: "<?= lang('App.feedback.empty_result') ?>",
        page: "<?= lang('App.general.page') ?>",
        of: "<?= lang('App.general.of') ?>",
        records: "<?= lang('App.general.records') ?>",
        result: "<?= lang('App.general.result') ?>",
        loading_definition_for: "<?= lang(
            'App.objects_browser.loading_definition_for',
        ) ?>",
        error_loading_definition: "<?= lang(
            'App.feedback.error_loading_definition',
        ) ?>",
        search_placeholder: "<?= lang('App.workspace.search_placeholder') ?>",
        no_templates: "<?= lang('App.feedback.no_templates') ?>",
        loading: "<?= lang('App.general.loading') ?>",
        job_name: "<?= lang('App.agent.job_name') ?>",
        status: "<?= lang('App.agent.status') ?>",
        last_run: "<?= lang('App.agent.last_run') ?>",
        last_run_status: "<?= lang('App.agent.last_run_status') ?>",
        next_run: "<?= lang('App.agent.next_run') ?>",
        start_job: "<?= lang('App.agent.start_job') ?>",
        stop_job: "<?= lang('App.agent.stop_job') ?>",
        running: "<?= lang('App.general.running') ?>",
        enable: "<?= lang('App.general.enable') ?>",
        enabled: "<?= lang('App.general.enabled') ?>",
        disable: "<?= lang('App.general.disable') ?>",
        disabled: "<?= lang('App.general.disabled') ?>",
        success: "<?= lang('App.general.success') ?>",
        failed: "<?= lang('App.general.failed') ?>",
        unknown: "<?= lang('App.general.unknown') ?>",
        no_jobs_found: "<?= lang('App.agent.no_jobs_found') ?>",
        view_job_history: "<?= lang('App.agent.history') ?>",
        no_history_found: "<?= lang('App.agent.no_history_found') ?>",
        error_retrieving_history: "<?= lang(
            'App.agent.error_retrieving_history',
        ) ?>",
        retry: "<?= lang('App.general.retry') ?>",
        canceled: "<?= lang('App.general.canceled') ?>",
        job_started: "<?= lang('App.agent.job_started') ?>",
        job_start_failed: "<?= lang('App.agent.job_start_failed') ?>",
        job_stopped: "<?= lang('App.agent.job_stopped') ?>",
        job_stop_failed: "<?= lang('App.agent.job_stop_failed') ?>",
        event_name: "<?= lang('App.event.event_name') ?>",
        disable_event: "<?= lang('App.event.disable_event') ?>",
        enable_event: "<?= lang('App.event.enable_event') ?>",
        no_primary_key: "<?= lang('App.workspace.no_primary_key') ?>",
        multiple_tables_not_supported: "<?= lang(
            'App.workspace.multiple_tables_not_supported',
        ) ?>",
        no_table_detected: "<?= lang('App.workspace.no_table_detected') ?>",
        confirm_discard_changes: "<?= lang(
            'App.workspace.confirm_discard_changes',
        ) ?>",
        error_no_db_selected_for_edit: "<?= lang(
            'App.feedback.error_no_db_selected_for_edit',
        ) ?>",
        error_saving: "<?= lang('App.workspace.error_saving') ?>",
        data_saved: "<?= lang('App.feedback.data_saved') ?>",
        no_pk_edit: "<?= lang('App.feedback.no_pk_edit') ?>",
        new_table: "<?= lang('App.schema_editor.new_table') ?>",
        design_table: "<?= lang('App.schema_editor.design_table') ?>",
        drop_table: "<?= lang('App.schema_editor.drop_table') ?>",
        confirm_drop_table: "<?= lang(
            'App.schema_editor.confirm_drop_table',
        ) ?>",
        stored_procedures: "<?= lang(
            'App.objects_browser.stored_procedures',
        ) ?>",
        script_execute: "<?= lang('App.objects_browser.script_execute') ?>",
        script_create: "<?= lang('App.schema_editor.script_create') ?>",
        script_alter: "<?= lang('App.schema_editor.script_alter') ?>",
        table_drop_successfully: "<?= lang(
            'App.schema_editor.table_drop_successfully',
        ) ?>",
        actions: "<?= lang('App.general.actions') ?>"
    };